db: introduce UsableSize flag in block volume Info
We should use newly expanded size on the block volume by growing filesystem on
the block device only when block volume is successfully expanded.

On partial failures (few nodes configured to size X and few nodes with size Y)
we should never proceed further for using the newly expanded size. This
might get us into block storage level inconsistencies.

To indicate the real usable size of a block volume, we have come up with
adding a new field to the block volume info.

Example 1:
---------
$ heketi-cli blockvolume expand 95aaa622f466bc4ae9e5d460ac55505b --new-size=5
Name: blockvol_95aaa622f466bc4ae9e5d460ac55505b
Size: 5
UsableSize: 5
Volume Id: 95aaa622f466bc4ae9e5d460ac55505b
Cluster Id: 71d6c0a8f6e88c1ddc84b78b464aafd9
Hosts: [192.168.121.55 192.168.121.206 192.168.121.253]
IQN: iqn.2016-12.org.gluster-block:3fe22613-c669-4b04-ab6b-de279c84ca77
LUN: 0
Hacount: 3
Username:
Password:
Block Hosting Volume: b0cb4b999f9d1d386b093c81480e3964

$ heketi-cli blockvolume info 95aaa622f466bc4ae9e5d460ac55505b
Name: blockvol_95aaa622f466bc4ae9e5d460ac55505b
Size: 5
UsableSize: 5
Volume Id: 95aaa622f466bc4ae9e5d460ac55505b
Cluster Id: 71d6c0a8f6e88c1ddc84b78b464aafd9
Hosts: [192.168.121.55 192.168.121.206 192.168.121.253]
IQN: iqn.2016-12.org.gluster-block:3fe22613-c669-4b04-ab6b-de279c84ca77
LUN: 0
Hacount: 3
Username:
Password:
Block Hosting Volume: b0cb4b999f9d1d386b093c81480e3964

Here 'Size' matches 'UsableSize', hence we can proceed further to grow fs on
the device and use the 5GiB Space completely.

Example 2:
---------
$ heketi-cli blockvolume expand 95aaa622f466bc4ae9e5d460ac55505b --new-size=10
Error: Failed to expand block volume: block volume resize failed: 192.168.121.55:[5.0 GiB] 192.168.121.206:[5.0 GiB] (see logs for details, and retry the operation)

$ heketi-cli blockvolume info 95aaa622f466bc4ae9e5d460ac55505b
Name: blockvol_95aaa622f466bc4ae9e5d460ac55505b
Size: 10
UsableSize: 5
Volume Id: 95aaa622f466bc4ae9e5d460ac55505b
Cluster Id: 71d6c0a8f6e88c1ddc84b78b464aafd9
Hosts: [192.168.121.55 192.168.121.206 192.168.121.253]
IQN: iqn.2016-12.org.gluster-block:3fe22613-c669-4b04-ab6b-de279c84ca77
LUN: 0
Hacount: 3
Username:
Password:
Block Hosting Volume: b0cb4b999f9d1d386b093c81480e3964

Here 'Size' doesn't match 'UsableSize', hence we shouldn't proceed further
to grow fs on the device, instead look at the logs, find and fix the real
problem and rerun the expand command again until we see a success i.e.
Size and UsableSize match.

Signed-off-by: Prasanna Kumar Kalever <prasanna.kalever@redhat.com>